// AlphaOS Office — DEMO data layer. Every value here is presentation-only
// demo evidence and must stay labelled DEMO in the UI. Live mode uses api.js.

export const AGENTS = [
  {
    id: "manager",
    name: "Manager",
    role: "投资经理",
    duty: "战略规划",
    status: "online",
    desk: 0,
    palette: { hair: "#e8e8e8", suit: "#1f2937", tie: "#22d3ee", skin: "#f0c8a0", extra: "beard" },
    specialty: "资产配置 · 策略制定 · 组合管理",
    desc: "统筹全局研究方向与资源分配，制定投资策略与组合方案，驱动团队协同执行与绩效优化。",
    joined: "2024-01-15",
    years: "12 年",
    completion: "98.6%",
    rating: 4.8,
    skillCount: 12,
    capabilities: [
      { label: "大类资产配置", pct: 95 },
      { label: "投资组合优化", pct: 92 },
      { label: "策略回测与评估", pct: 90 },
      { label: "风险收益分析", pct: 93 },
      { label: "团队协同管理", pct: 96 },
    ],
    radar: { labels: ["策略制定", "组合管理", "风险控制", "数据分析", "资产配置"], values: [92, 88, 80, 84, 95] },
    skills: [
      { name: "资产配置优化", type: "策略类" },
      { name: "组合构建", type: "策略类" },
      { name: "风险收益分析", type: "分析类" },
      { name: "宏观因子分析", type: "分析类" },
      { name: "绩效归因", type: "分析类" },
      { name: "市场情景预测", type: "预测类" },
      { name: "再平衡策略", type: "交易类" },
      { name: "策略回测", type: "交易类" },
    ],
    recentTasks: [
      { title: "2024Q2 大类资产配置策略", tag: "策略制定", status: "done", time: "10:23" },
      { title: "全球宏观周报 2024-05-26", tag: "宏观分析", status: "done", time: "09:48" },
      { title: "组合优化与再平衡建议", tag: "组合管理", status: "done", time: "昨天 16:30" },
      { title: "投资组合月度绩效评估", tag: "绩效评估", status: "done", time: "05-24 11:15" },
    ],
    contributions: ["明确研究框架", "制定执行计划"],
    planner: true,
  },
  {
    id: "macro",
    name: "Macro",
    role: "宏观分析师",
    duty: "宏观分析",
    status: "online",
    desk: 1,
    palette: { hair: "#9aa4b0", suit: "#243447", tie: "#f59e0b", skin: "#eec39a", extra: "moustache" },
    specialty: "宏观经济 · 政策分析 · 全球大势",
    desc: "跟踪全球宏观经济与政策动向，分析周期趋势与结构变化，评估宏观对大类资产的影响。",
    joined: "2024-01-15",
    years: "15 年",
    completion: "97.2%",
    rating: 4.7,
    skillCount: 8,
    capabilities: [
      { label: "宏观周期研判", pct: 93 },
      { label: "政策解读", pct: 91 },
      { label: "利率与流动性", pct: 89 },
      { label: "全球资产配置", pct: 86 },
    ],
    radar: { labels: ["宏观洞察", "政策分析", "数据处理", "风险控制", "报告输出"], values: [95, 90, 82, 78, 84] },
    skills: [
      { name: "宏观数据解读", type: "分析类" },
      { name: "政策事件评估", type: "分析类" },
      { name: "利率情景分析", type: "预测类" },
      { name: "流动性监控", type: "监控类" },
    ],
    recentTasks: [
      { title: "全球宏观周报 2024-05-26", tag: "宏观分析", status: "done", time: "09:48" },
      { title: "美联储议息前瞻", tag: "政策分析", status: "done", time: "05-25 15:20" },
    ],
    contributions: ["政策与经济分析", "产业驱动判断"],
  },
  {
    id: "research",
    name: "Research",
    role: "行业研究员",
    duty: "行业研究",
    status: "working",
    desk: 2,
    palette: { hair: "#f2f2f2", suit: "#312e45", tie: "#34d399", skin: "#f0c8a0", extra: "none" },
    specialty: "行业研究 · 公司分析 · 估值建模",
    desc: "深度研究行业与公司基本面，挖掘投资机会，输出高质量研究结论与估值观点。",
    joined: "2024-01-15",
    years: "10 年",
    completion: "96.8%",
    rating: 4.6,
    skillCount: 15,
    capabilities: [
      { label: "行业格局分析", pct: 94 },
      { label: "公司基本面", pct: 92 },
      { label: "产业链梳理", pct: 90 },
      { label: "估值建模", pct: 88 },
    ],
    radar: { labels: ["行业研究", "公司分析", "估值建模", "数据处理", "报告输出"], values: [94, 92, 86, 80, 82] },
    skills: [
      { name: "A股个股档案", type: "研究类" },
      { name: "行业对比", type: "研究类" },
      { name: "财务分析", type: "分析类" },
      { name: "估值建模", type: "分析类" },
      { name: "舆情监控", type: "监控类" },
    ],
    recentTasks: [
      { title: "宁德时代深度研究", tag: "公司研究", status: "running", time: "进行中" },
      { title: "新能源行业月度跟踪", tag: "行业研究", status: "done", time: "05-26 18:02" },
    ],
    contributions: ["行业深度研究", "产业链梳理"],
  },
  {
    id: "quant",
    name: "Quant",
    role: "量化分析师",
    duty: "量化建模",
    status: "online",
    desk: 3,
    palette: { hair: "#6b7280", suit: "#1e3a3a", tie: "#a78bfa", skin: "#eec39a", extra: "glasses" },
    specialty: "量化建模 · 因子研究 · 统计学习",
    desc: "构建与优化量化模型与交易策略，进行因子挖掘与回测验证，驱动数据化投资决策。",
    joined: "2024-01-15",
    years: "9 年",
    completion: "95.9%",
    rating: 4.7,
    skillCount: 16,
    capabilities: [
      { label: "因子挖掘", pct: 93 },
      { label: "策略回测", pct: 91 },
      { label: "统计建模", pct: 90 },
      { label: "数据处理", pct: 94 },
    ],
    radar: { labels: ["量化建模", "数据处理", "策略制定", "风险控制", "报告输出"], values: [95, 94, 82, 76, 74] },
    skills: [
      { name: "因子构想生成", type: "研究类" },
      { name: "R020 量能因子", type: "计算类" },
      { name: "估值建模", type: "分析类" },
      { name: "统计套利扫描", type: "策略类" },
    ],
    recentTasks: [
      { title: "红利低波组合增强策略回测", tag: "策略回测", status: "running", time: "进行中" },
      { title: "R020 成交量放大因子计算", tag: "因子计算", status: "done", time: "05-26 11:40" },
    ],
    contributions: ["数据建模预测", "投资机会评分"],
  },
  {
    id: "risk",
    name: "Risk",
    role: "风险分析师",
    duty: "风险监控",
    status: "busy",
    desk: 4,
    palette: { hair: "#4b5563", suit: "#3f2a2a", tie: "#f87171", skin: "#e8b88f", extra: "moustache" },
    specialty: "风险管理 · 压力测试 · 组合风控",
    desc: "监控组合风险与市场冲击，进行压力测试与情景分析，提出风控建议与应对方案。",
    joined: "2024-01-15",
    years: "11 年",
    completion: "97.8%",
    rating: 4.8,
    skillCount: 9,
    capabilities: [
      { label: "风险因子识别", pct: 94 },
      { label: "压力测试", pct: 92 },
      { label: "回撤控制", pct: 90 },
      { label: "流动性监控", pct: 88 },
    ],
    radar: { labels: ["风险控制", "数据分析", "宏观洞察", "量化建模", "报告输出"], values: [96, 84, 78, 72, 80] },
    skills: [
      { name: "风险扫描", type: "监控类" },
      { name: "情景压力测试", type: "分析类" },
      { name: "波动率建模", type: "分析类" },
    ],
    recentTasks: [
      { title: "组合流动性风险排查", tag: "风险扫描", status: "running", time: "进行中" },
      { title: "极端行情压力测试", tag: "压力测试", status: "done", time: "05-25 17:12" },
    ],
    contributions: ["风险因子识别", "情景压力测试"],
  },
  {
    id: "report",
    name: "Report",
    role: "研究报告专员",
    duty: "报告生成",
    status: "online",
    desk: 5,
    palette: { hair: "#e5e7eb", suit: "#2a2f4a", tie: "#60a5fa", skin: "#f0c8a0", extra: "beard" },
    specialty: "报告撰写 · 数据可视化 · 论证推理",
    desc: "整合研究成果，生成专业投资报告与可视化图表，输出清晰观点与决策支持材料。",
    joined: "2024-01-15",
    years: "8 年",
    completion: "98.1%",
    rating: 4.6,
    skillCount: 10,
    capabilities: [
      { label: "报告撰写", pct: 95 },
      { label: "图表可视化", pct: 92 },
      { label: "证据链整合", pct: 90 },
      { label: "观点提炼", pct: 89 },
    ],
    radar: { labels: ["报告输出", "数据处理", "行业研究", "风险控制", "策略制定"], values: [96, 84, 76, 74, 70] },
    skills: [
      { name: "报告自动生成", type: "输出类" },
      { name: "图表引擎", type: "输出类" },
      { name: "证据链校验", type: "分析类" },
    ],
    recentTasks: [
      { title: "新能源行业投资机会研究报告", tag: "报告撰写", status: "done", time: "04-30 10:35" },
      { title: "AI 投研团队周会纪要", tag: "团队协同", status: "done", time: "05-23 17:02" },
    ],
    contributions: ["结论输出", "可视化呈现"],
  },
];

export const TEAM_RADAR = {
  labels: ["宏观洞察", "行业研究", "量化建模", "风险控制", "数据处理", "报告输出"],
  values: [86, 90, 88, 84, 92, 89],
};

export const RECOMMENDED_GROUPS = [
  ["⚡ 分析新能源行业机会", "🍶 评估贵州茅台的基本面与风险", "📈 寻找近期放量突破股票"],
  ["🔋 宁德时代深度研究", "🌏 全球宏观周报解读", "🛡 组合流动性风险排查"],
  ["💊 创新药板块竞争格局", "🏦 红利低波策略回测", "🤖 AI 算力产业链梳理"],
];

export const OFFICE_FEED = [
  "量化专家 正在回测「红利低波组合增强策略」…",
  "行业研究员 完成锂电产业链格局梳理",
  "宏观分析师 更新美债利率情景假设",
  "风险分析师 触发流动性风险扫描",
  "研究报告专员 正在排版《新能源行业报告》",
];

export const SKILL_META = {
  财务分析: { desc: "拆解三表与盈利质量，输出财务健康度评分。", by: ["research"] },
  行业对比: { desc: "横向对比同业关键指标，定位相对竞争力。", by: ["research"] },
  估值建模: { desc: "DDM / 相对估值 / 情景估值模型构建与求解。", by: ["quant", "research"] },
  风险扫描: { desc: "扫描集中度、流动性与波动率风险信号。", by: ["risk"] },
  舆情监控: { desc: "跟踪新闻与公告舆情，标记情绪拐点。", by: ["research"] },
};

// ---------- war-room demo script ----------
// t 单位为秒（1x 速度）。type: log / dag / work / say / visit / roundtable /
// done / skill / timeline / finish
export const DEMO_TASK = {
  id: "task-catl",
  title: "【公司深度研究】宁德时代（300750.SZ）",
  short: "宁德时代（300750.SZ）",
  type: "公司深度研究",
  started: "10:15:23",
  eta: "14:32:00",
  priority: "高",
  goal: "全面分析公司基本面、行业格局、盈利能力与估值水平，形成投资建议。",
  status: "running",
  kind: "公司研究",
  time: "今天 10:15",
};

export const WAR_SCRIPT = [
  { t: 1, type: "timeline", label: "任务创建", clock: "10:15" },
  { t: 1, type: "log", agent: "系统", text: "任务开始执行", color: "#7fa3c7" },
  { t: 2, type: "work", agent: "manager" },
  { t: 2, type: "say", agent: "manager", text: "我来拆解任务：宏观、行业、量化三线并行，风险与报告收尾。", dur: 4 },
  { t: 5, type: "dag", agent: "manager", status: "done" },
  { t: 5, type: "timeline", label: "任务拆解完成", clock: "10:20" },
  { t: 5, type: "log", agent: "Manager", text: "完成任务拆解与分配", color: "#22d3ee" },
  { t: 6, type: "work", agent: "macro" },
  { t: 6, type: "dag", agent: "macro", status: "working" },
  { t: 7, type: "say", agent: "macro", text: "先拉取近 24 个月宏观与流动性数据…", dur: 4 },
  { t: 7, type: "log", agent: "Macro", text: "开始宏观环境研判", color: "#f59e0b" },
  { t: 8, type: "work", agent: "research" },
  { t: 8, type: "dag", agent: "research", status: "working" },
  { t: 9, type: "say", agent: "research", text: "梳理锂电产业链与竞争格局…", dur: 4 },
  { t: 10, type: "work", agent: "quant" },
  { t: 10, type: "dag", agent: "quant", status: "working" },
  { t: 11, type: "say", agent: "quant", text: "构建 DDM 估值模型与因子暴露…", dur: 4 },
  { t: 12, type: "skill", name: "财务分析", n: 5 },
  { t: 12, type: "log", agent: "Research", text: "调用 Skill「财务分析」解析三表", color: "#34d399" },
  { t: 15, type: "visit", from: "quant", to: "macro", lines: [
    { agent: "quant", text: "需要美债利率与 PMI 的最新读数。" },
    { agent: "macro", text: "已发你，注意 6 月数据有下修。" },
  ] },
  { t: 15, type: "log", agent: "Quant", text: "向 Macro 请求宏观数据接口", color: "#a78bfa" },
  { t: 18, type: "skill", name: "估值建模", n: 6 },
  { t: 19, type: "say", agent: "research", text: "行业格局已清晰：一超多强，份额向龙头集中。", dur: 4 },
  { t: 22, type: "done", agent: "macro" },
  { t: 22, type: "timeline", label: "Macro 完成", clock: "10:21" },
  { t: 22, type: "log", agent: "Macro", text: "已完成宏观环境研判", color: "#f59e0b" },
  { t: 24, type: "roundtable", agents: ["macro", "research", "quant"], lines: [
    { agent: "research", text: "基本面上修盈利预期约 6%。" },
    { agent: "quant", text: "对应 DDM 目标区间上调 8%。" },
    { agent: "macro", text: "利率情景中性，不压制估值。" },
  ] },
  { t: 24, type: "log", agent: "系统", text: "专家圆桌对齐：盈利预期与估值口径", color: "#7fa3c7" },
  { t: 30, type: "done", agent: "research" },
  { t: 30, type: "timeline", label: "Research 完成", clock: "10:22" },
  { t: 30, type: "log", agent: "Research", text: "已完成行业格局分析", color: "#34d399" },
  { t: 32, type: "work", agent: "risk" },
  { t: 32, type: "dag", agent: "risk", status: "running" },
  { t: 32, type: "timeline", label: "Risk 进行中", clock: "10:24" },
  { t: 33, type: "say", agent: "risk", text: "扫描流动性与集中度风险…", dur: 4 },
  { t: 33, type: "log", agent: "Risk", text: "触发流动性风险扫描", color: "#f87171" },
  { t: 36, type: "skill", name: "风险扫描", n: 6 },
  { t: 38, type: "done", agent: "quant" },
  { t: 38, type: "timeline", label: "Quant 完成", clock: "10:25" },
  { t: 38, type: "log", agent: "Quant", text: "完成估值模型（DDM）", color: "#a78bfa" },
  { t: 40, type: "work", agent: "report" },
  { t: 40, type: "dag", agent: "report", status: "working" },
  { t: 41, type: "say", agent: "report", text: "汇总证据链，生成报告大纲…", dur: 4 },
  { t: 42, type: "skill", name: "行业对比", n: 8 },
  { t: 46, type: "say", agent: "risk", text: "集中度中等偏低，触发一次压力测试。", dur: 4 },
  { t: 50, type: "done", agent: "risk" },
  { t: 50, type: "log", agent: "Risk", text: "完成风险扫描与压力测试", color: "#f87171" },
  { t: 52, type: "skill", name: "舆情监控", n: 9 },
  { t: 56, type: "done", agent: "report" },
  { t: 56, type: "timeline", label: "报告生成", clock: "10:28" },
  { t: 56, type: "log", agent: "Report", text: "研究报告已生成并通过证据校验", color: "#60a5fa" },
  { t: 58, type: "skill", name: "估值建模", n: 15 },
  { t: 58, type: "skill", name: "财务分析", n: 12 },
  { t: 60, type: "finish" },
  { t: 60, type: "log", agent: "系统", text: "AlphaOS 任务处理完成", color: "#7fa3c7" },
];

export const SKILL_FINAL_COUNTS = { 财务分析: 12, 行业对比: 8, 估值建模: 15, 风险扫描: 6, 舆情监控: 9 };

export const HISTORY_TASKS = [
  { id: "task-macro-weekly", title: "全球宏观周报 2024-05-26", status: "done", kind: "宏观分析", time: "昨天 16:30" },
  { id: "task-moutai", title: "贵州茅台基本面与风险评估", status: "done", kind: "公司研究", time: "05-24 11:15" },
  { id: "task-dividend", title: "红利低波组合增强策略回测", status: "running", kind: "策略回测", time: "今天 09:48" },
];

// ---------- clarification chat ----------
export const CLARIFY_GROUPS = [
  { key: "period", title: "投资周期", hint: "你希望的投资周期是？", multi: false, items: ["短期（1-3个月）", "中期（3-12个月）", "长期（1-3年）"], def: [2] },
  { key: "risk", title: "风险偏好", hint: "你的风险承受偏好是？", multi: false, items: ["保守型（低风险）", "稳健型（中风险）", "进取型（高风险）"], def: [2] },
  { key: "focus", title: "研究重点", hint: "本次研究的核心关注点是？", multi: false, items: ["财务与估值", "行业与竞争格局", "自动驾驶与机器人业务"], def: [2] },
  { key: "dims", title: "分析维度", hint: "希望包含哪些分析维度？", multi: true, allItem: "以上全部", items: ["基本面分析", "技术面分析", "情景与敏感性分析", "以上全部"], def: [3] },
];

export const ANALYSIS_SCOPE = [
  "公司基本面与财务分析",
  "自动驾驶业务（FSD）深入分析",
  "机器人业务（Optimus）深入分析",
  "行业竞争格局与对比",
  "估值分析与情景预测",
  "风险因素识别与敏感性分析",
];

// ---------- report ----------
export const REPORTS = [
  {
    id: "r-ne-20240430",
    title: "新能源行业投资机会研究报告",
    taskNo: "TASK-20240430-NE001",
    doneAt: "2024-04-30 10:35",
    horizon: "中期（6-12 个月）",
    score: 95,
    scoreDims: { 专业度: 96, 深度: 94, 完整度: 95 },
    status: "done",
    kind: "行业研究",
    team: ["manager", "macro", "research", "quant", "risk", "report"],
    summary:
      "新能源行业在政策驱动与技术迭代双重催化下，长期成长逻辑清晰。我们看好储能、海风、一体化组件等细分方向，建议关注具备技术壁垒与全球化布局的龙头企业。",
    tags: ["中期机会", "政策驱动", "技术迭代", "全球化", "高景气赛道"],
    trend: {
      title: "行业景气度趋势",
      labels: ["2022", "2023", "2024E", "2025E"],
      series: [
        { name: "新能源整体景气度", color: "#34d399", data: [18, 38, 66, 92] },
        { name: "沪深300", color: "#3b82f6", data: [8, 20, 26, 30] },
      ],
    },
    tracks: [
      { name: "储能系统", v: 92 },
      { name: "海上风电", v: 88 },
      { name: "光伏一体化", v: 85 },
      { name: "氢能产业链", v: 72 },
      { name: "充电桩运营", v: 68 },
    ],
    kv: [
      { label: "行业复合增速 (2023-2026E)", value: "+28.6%", sub: "储能/海风领先", color: "green" },
      { label: "政策支持强度", value: "高", sub: "持续加码", color: "yellow" },
      { label: "资本开支趋势 (2024E)", value: "+62.3%", sub: "同比增长", color: "green" },
      { label: "重点推荐赛道", value: "储能·海风", sub: "光伏一体化", color: "blue" },
      { label: "风险等级", value: "中等偏低", sub: "关注产能过剩", color: "yellow" },
    ],
    contributions: {
      manager: ["明确研究框架", "制定执行计划"],
      macro: ["政策与经济分析", "产业驱动判断"],
      research: ["行业深度研究", "产业链梳理"],
      quant: ["数据建模预测", "投资机会评分"],
      risk: ["风险因子识别", "情景压力测试"],
      report: ["结论输出", "可视化呈现"],
    },
    body: [
      { h: "一、核心结论", p: "新能源行业处于政策与技术的双重上行周期。储能与海上风电的景气度与盈利确定性最强，给予「超配」建议；光伏一体化关注成本曲线左侧龙头；氢能与充电桩维持「标配」，等待商业化拐点。" },
      { h: "二、行业景气度", p: "2022-2025E 行业景气度由 18 提升至 92（内部指数），同期沪深300 景气度基本持平。结构上看，储能装机 2024E 同比 +120%，海上风电吊装同比 +65%，构成景气主引擎。" },
      { h: "三、重点赛道评分", p: "储能系统 92 分（政策+经济性双击）、海上风电 88 分（竞配加速、深远海打开空间）、光伏一体化 85 分（盈利底部反转）、氢能产业链 72 分、充电桩运营 68 分。" },
      { h: "四、风险提示", p: "产能过剩引发的盈利下修、海外贸易政策扰动、利率上行压制估值。压力测试显示组合在极端情景下最大回撤约 12%，处于可接受区间。" },
    ],
    quickAsks: [
      "如果把投资周期改为长期（3-5年），策略是否需要调整？",
      "对比宁德时代 vs 比亚迪，谁更值得投资？",
      "为什么储能系统的评分最高？",
      "补充宏观分析视角",
    ],
    followReplies: [
      { match: ["长期", "3-5", "周期"], reply: "好的，已切换至长期视角：拉长到 3-5 年，储能与海风的成长确定性不变，但光伏一体化的排序上升——行业出清后龙头盈利弹性更大。建议把「技术迭代」权重从 20% 上调至 30%，并新增氢能作为远期期权仓位。" },
      { match: ["宁德", "比亚迪", "对比", "谁更"], reply: "正在从盈利能力、成长性、估值等维度进行对比分析：宁德时代毛利率 26.5% vs 比亚迪 22.1%；研发投入强度 7.2% vs 6.1%；2024E P/E 分别为 18x 与 21x。短期赔率比亚迪更优（整车+电池双轮），长期胜率宁德时代更高（技术壁垒+全球份额）。详细对比表已加入报告附录。" },
      { match: ["储能", "评分", "最高"], reply: "储能系统 92 分的核心驱动：① 2024E 国内大储装机同比 +120%，招标价格企稳；② 峰谷价差扩大使工商业储能 IRR 突破 12%；③ 海外大储订单可见度已到 2025H2。三项驱动的可持续性评分均为 A。" },
      { match: ["宏观", "视角"], reply: "已补充宏观视角：当前处于「宽货币+宽财政」组合，利率中枢下移利好长久期成长资产；海外降息周期开启将改善新能源出口链的融资环境。宏观维度对行业景气度的边际贡献为 +6。" },
      { match: ["风险"], reply: "主要风险再梳理：① 产能过剩——电池环节产能利用率约 65%，出清仍需 2-3 个季度；② 贸易政策——海外关税情景已计入 -8% 盈利敏感性；③ 技术路线——固态电池若提前量产将重构竞争格局，建议每季度跟踪验证。" },
      { match: [], reply: "收到，我会基于报告的证据链继续深挖这个问题，并把结论同步到报告附录。（DEMO 应答）" },
    ],
  },
  {
    id: "r-moutai-20240524",
    title: "贵州茅台基本面与风险评估",
    taskNo: "TASK-20240524-MT002",
    doneAt: "2024-05-24 11:15",
    horizon: "长期（1-3 年）",
    score: 91,
    scoreDims: { 专业度: 92, 深度: 90, 完整度: 91 },
    status: "done",
    kind: "公司研究",
    team: ["manager", "research", "quant", "risk", "report"],
    summary: "贵州茅台盈利质量与现金流仍处于行业顶端，批价企稳是短期关键信号；估值处于历史中枢下沿，风险收益比改善。",
    tags: ["白酒龙头", "盈利质量", "估值修复"],
    trend: {
      title: "盈利质量趋势",
      labels: ["2022", "2023", "2024E", "2025E"],
      series: [
        { name: "ROE(%)", color: "#34d399", data: [30, 32, 33, 34] },
        { name: "行业均值", color: "#3b82f6", data: [18, 19, 19, 20] },
      ],
    },
    tracks: [
      { name: "盈利质量", v: 95 },
      { name: "现金流", v: 93 },
      { name: "估值安全边际", v: 82 },
      { name: "需求景气", v: 74 },
    ],
    kv: [
      { label: "ROE (2024E)", value: "33%", sub: "行业第一", color: "green" },
      { label: "股息率", value: "2.8%", sub: "持续提升", color: "blue" },
      { label: "估值分位", value: "22%", sub: "近五年", color: "yellow" },
      { label: "风险等级", value: "低", sub: "批价波动", color: "green" },
      { label: "现金储备", value: "充裕", sub: "净现金", color: "green" },
    ],
    contributions: {
      manager: ["研究框架", "执行计划"],
      research: ["基本面拆解", "渠道调研"],
      quant: ["估值模型", "分位测算"],
      risk: ["情景压力测试"],
      report: ["结论输出", "可视化呈现"],
    },
    body: [
      { h: "一、核心结论", p: "基本面顶端 + 估值低位，具备长期配置价值；短期跟踪批价与渠道库存两个高频信号。" },
      { h: "二、风险提示", p: "需求复苏不及预期、批价二次探底、消费税改革预期扰动。" },
    ],
    quickAsks: ["批价企稳的确认信号有哪些？", "对比五粮液，谁的风险收益比更好？", "消费税改革影响几何？"],
    followReplies: [
      { match: [], reply: "收到，我会基于报告证据链继续分析这个问题。（DEMO 应答）" },
    ],
  },
];

export const SOON_PAGES = {
  skills: { ico: "🧩", name: "Skills", desc: "集中管理投研团队的技能市场：浏览、安装、审查每个 Skill 的来源、许可与状态。当前技能由后端 skill_registry 统一托管，前端管理台规划中。" },
  "data-market": { ico: "🗄️", name: "数据市场", desc: "一站式接入行情、财报、宏观与另类数据源，统一鉴权与配额管理。规划接入 PandaData 目录浏览。" },
  strategies: { ico: "📦", name: "策略库", desc: "沉淀可复用的研究与回测策略模板，支持版本管理与一键复跑。规划中。" },
  monitor: { ico: "📊", name: "监控看板", desc: "实时监控系统吞吐、任务成功率、模型调用配额与数据延迟，规划中。" },
  knowledge: { ico: "📚", name: "知识库", desc: "沉淀研究方法论、术语词典与历史结论，供团队检索复用，规划中。" },
};
